### ISSUE TITLE
I reported an error when using the image installation

### ISSUE THREAD

**Issue by Jack-Ywn** [oVirt/ovirt-node-ng-image#82]
**Describe the bug**
An error occurred while the system installation was complete

**Screenshots**
![安装报错](https://user-images.githubusercontent.com/72083949/187929835-5f2f5cf3-e078-4053-a660-39c2aa9e37b7.png)

**After exiting the installation, you can enter the system normally, but the following error message is displayed**

**This error occurred when I tried to install the following versions**
ovirt-node-ng-installer-4.3.10-2020060117.el7.iso
ovirt-node-ng-installer-4.4.10-2022030308.el8.iso

`Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/nodectl/__main__.py", line 42, in <module>
    CliApplication()
  File "/usr/lib/python2.7/site-packages/nodectl/__init__.py", line 200, in CliApplication
    return cmdmap.command(args)
  File "/usr/lib/python2.7/site-packages/nodectl/__init__.py", line 118, in command
    return self.commands[command](**kwargs)
  File "/usr/lib/python2.7/site-packages/nodectl/__init__.py", line 101, in motd
    Motd(Status(Health(self.imgbased).status(),
  File "/usr/lib/python2.7/site-packages/imgbased/plugins/core.py", line 358, in status
    status.results.append(group().run())
  File "/usr/lib/python2.7/site-packages/imgbased/plugins/core.py", line 385, in check_thin
    pool = self.app.imgbase._thinpool()
  File "/usr/lib/python2.7/site-packages/imgbased/imgbase.py", line 120, in _thinpool
    return LVM.Thinpool.from_tag(self.thinpool_tag)
  File "/usr/lib/python2.7/site-packages/imgbased/lvm.py", line 227, in from_tag
    assert len(lvs) == 1
AssertionError
Admin Console: https://10.11.1.16:9090/
`

**Comment by sandrobonazzola** [comment]
Closing this as End Of Life. Please upgrade to oVirt 4.5 as soon as practical.
